version = "1.4-dev1"
versionCode = 1032
timestamp = 1696865000
channel = "PREVIEW"

[notes.en]
highlights = []
items = [
    "New: customizable list item layout style with more options",
    "Fix: try to fix playback and queue got frozen at startup",
    "Improvement: add Shuffle Mode and Repeat Mode buttons in Notification (since Android T) and Android Auto",
    "Improvement: display album artwork in Android Auto (basic support)",
    "Modify: replace some icons",
    "Modify: show song order instead of images in Playlist Detail",
    "Development: use webp and svg formats in assets and resource to shrink artifacts size",
]

[notes.zh]
highlights = []
items = [
    "新增 可定制列表项样式",
    "修复 尝试修复播放和队列在启动时冻结",
    "改进 在通知(Android T 及以上)和 Android Auto 中, 添加随机模式和重复模式按钮",
    "改进 在 Android Auto 中, 显示专辑封面 (仅基本支持)",
    "修改 替换部分图标",
    "修改 在 播放列表详情 中, 显示歌曲顺序而非图片",
    "开发 使用 webp 和 svg 格式以减少大小",
]