version = "1.4-dev2"
versionCode = 1033
timestamp = 1697446000
channel = "PREVIEW"

[notes.en]
highlights = []
items = [
    "Fix: in Main Player, PlayPause button sometimes gets frozen and has glitchy animation",
    "Fix: in Main Player, palette color is not correctly updated if you change current song too quickly",
    "Fix: in Main Player, legibility of \"Up Next\" text (color)",
    "Fix: in Main Player, sometimes controls and queue may disappear or cover the partial of images",
]

[notes.zh]
highlights = []
items = [
    "修复 主播放器内, 暂停播放按钮有时会卡住和动画异常",
    "修复 主播放器内, 主色调无法正确更新若切歌过快",
    "修复 主播放器内, \"接下来\"文本颜色问题",
    "修复 主播放器内, 有时控件和队列可能会消失不见或覆盖部分图片",
]