version = "1.2-dev7"
versionCode = 1015
timestamp = 1695297454
channel = "PREVIEW"


[notes.en]
highlights = []
items = [
    "Improve: customizable upgrade check interval",
    "Improve: customizable last added playlist cutoff interval",
    "Improve: Online Search Texts",
    "New: Time Duration Picker",
]


[notes.zh]
highlights = []
items = [
    "改进 自定义检查更新时间间隔",
    "改进 自定义最后添加播放列表截止时间间隔",
    "改进 在线搜索文本",
    "新增 时间长度选择器",
]

