version = "1.3.1"
versionCode = 1031
timestamp = 1696350000
channel = "STABLE"

[notes.en]
highlights = []
items = [
    "Fix: crash when sending the playback notification on Android U",
    "Fix: some albums cover artworks not showing",
    "Fix: various minor bugs in Android Auto",
    "Improvement: show Genres and Playlists in Android Auto",
    "Improvement: check existences of songs in playing queue at start-up",
    "Improvement: loading of Artists and Albums",
    "Development: upgrade APG to 8.1.2, upgrade dependencies, cleanup code",
]

[notes.zh]
highlights = []
items = [
    "修复 Android U 上弹出播放通知时崩溃",
    "修复 某些专辑的封面艺术不显示",
    "修复 大量 Android Auto 上的问题",
    "改进 在 Android Auto 中显示全部流派和全部播放列表",
    "改进 启动时检查播放队列中歌曲是否存在",
    "改进 艺术家和专辑加载",
    "开发 升级APG依赖8.1.2, 更新依赖, 清理代码",
]