version = "1.3.1-dev0"
versionCode = 1030
timestamp = 1696170000
channel = "PREVIEW"

[notes.en]
highlights = []
items = [
    "Fix: some albums' cover artwork not showing",
    "Improvement: loading of Artists and Albums",
    "Development: upgrade APG to 8.1.2, upgrade dependicies, cleanup code",
]

[notes.zh]
highlights = []
items = [
    "修复 某些专辑的封面艺术不显示",
    "改进 艺术家和专辑加载",
    "开发 升级APG依赖8.1.2, 更新依赖, 清理代码",
]