version = "1.3.0"
versionCode = 1030
timestamp = 1695789000
channel = "STABLE"

[notes.en]
highlights = []
items = [
    "Development: upgrade targetSdk to 34",
    "Fix: albums color footer in Artist Detail can not refresh after changing",
    "Improvement: add 'Disable realtime local search' option, this would be helpful for fixing some IMEs can not show Candidate Bar if inline composition enabled, especially for some CJK IMEs",
    "Improvement: avoid sending internal error notifications if failing to load lyrics",
    "Development: upgrade dependencies, cleanup code",
    "Translation: update Portuguese, Brazilian (by EddieMattos)",
]

[notes.zh]
highlights = []
items = [
    "开发 升级 targetSdk 至 34",
    "修复 艺术家详细中的专辑页脚着色在更改后无法刷新",
    "改进 加载歌词时避免发送内部错误通知",
    "改进 添加‘关闭本地实时搜索’选项, 用于解决某些启用'内嵌输入'的输入法无法显示候选栏的问题, 尤其针对某些中日韩输入法",
    "开发 更新依赖, 清理代码",
    "翻译 更新巴西葡萄牙语(EddieMattos)",
]