version = "1.3.2"
versionCode = 1032
timestamp = 1697775000
channel = "STABLE"

[notes.en]
highlights = []
items = [
    "Fix: in Main Player, PlayPause button sometimes gets frozen and has glitchy animation",
    "Fix: in Main Player, palette color is not correctly updated when changing current song too quickly",
    "Fix: in Main Player, legibility of \"Up Next\" text (color)",
    "Fix: in Main Player, sometimes controls and queue may disappear or cover the partial of images",
    "Fix: playback and queue got frozen at startup",
]

[notes.zh]
highlights = []
items = [
    "修复 主播放器内, 暂停播放按钮有时会卡住与动画异常",
    "修复 主播放器内, 主色调无法正确更新若切歌过快",
    "修复 主播放器内, \"即将播放\"文本颜色问题",
    "修复 主播放器内, 有时控件和队列可能会消失不见或覆盖部分图片",
    "修复 修复播放控件和队列在启动时冻结",
]