name: action_test
on:
  push:
    tags:
      - "test_*"
    paths-ignore:
      - "README.md"
      - "version.json"
  workflow_dispatch:

jobs:
  build:
    name: test
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v2.2.0
