name: ci
on:
  push:
    branches:
      - 'dev'
      - 'release'
    tags-ignore:
      - 'preview_*'
      - 'v0*'
      - 'r_*'
      - 'test_*'
    paths-ignore:
      - 'README.md'
      - 'version'
      - 'version.json'
      - 'ReleaseNote.md'
      - '.github/workflows/preview_release.yml'
      - '.github/workflows/action_test.yml'
  workflow_dispatch:
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - 'README.md'
      - 'version'
      - 'version.json'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
#      - uses: gradle/wrapper-validation-action@v1 # its timeout fails the action

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

#      # now we are use Android Gradle Plugin 7.0.*
#
#      - name: Create DX links for BuildTools
#        run: ln -s $ANDROID_HOME/build-tools/31.0.0/d8 $ANDROID_HOME/build-tools/31.0.0/dx && ln -s $ANDROID_HOME/build-tools/31.0.0/lib/d8.jar $ANDROID_HOME/build-tools/31.0.0/lib/dx.jar
#        # we are using Android Gradle Plugin 4.x.x, which can not find 'dx' in SDK31
#


      - name: Build with Gradle
        run: ./gradlew assembleCi --stacktrace


      - name: signing apk
        uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: 31.0.0
        with:
          releaseDirectory: ./app/build/outputs/apk/ci
          signingKeyBase64: ${{ secrets.KEY }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ci_build
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          retention-days: 3

