name: dev
on:
  push:
    branches:
      - 'dev'
    tags-ignore:
      - 'preview_*'
      - 'v0*'
    paths-ignore:
      - 'README.md'
      - 'ReleaseNote.md'
      - 'version.json'
      - '.github/**'
      - 'crowdin.yml'
      - 'fastlane/metadata/android/**'
  workflow_dispatch:
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - 'README.md'
      - 'ReleaseNote.md'
      - 'version.json'
      - '.github/**'
      - 'crowdin.yml'
      - 'fastlane/metadata/android/**'

jobs:
  build:
    name: Build Dev CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle (Assemble CheckoutDebug)
        run: |
          ./gradlew assembleCheckoutDebug --stacktrace --parallel

      - name: Signing Apk
        uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: 33.0.0
        with:
          releaseDirectory: ./app/build/outputs/apk/checkout/debug
          signingKeyBase64: ${{ secrets.KEY }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v2.3.1
        with:
          name: dev
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
          retention-days: 3

