name: dev
on:
  push:
    branches:
      - 'dev'
      - 'main'
    tags-ignore:
      - 'v0*'
      - 'preview_*'
      - 'test*'
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - 'crowdin.yml'
      - 'fastlane/metadata/android/**'
      - 'tools/**'
      - 'fdroid.properties'
      - '*.json'
      - '**.md'
  workflow_dispatch:
  pull_request:
    branches:
      - 'dev'
      - 'main'
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - 'crowdin.yml'
      - 'fastlane/metadata/android/**'
      - 'tools/**'
      - 'fdroid.properties'
      - '*.json'
      - '**.md'

jobs:
  build:
    name: Build Dev CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Generate Sign Config
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/key.jdk
          CONFIG_FILE: ${{ github.workspace }}/signing.properties
        run: |
          # recover keystore from base64
          echo "${{ secrets.KEY }}"  | base64 -d > $KEYSTORE_FILE
          # write signing.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> $CONFIG_FILE
          echo "storeFile=$KEYSTORE_FILE"                    >> $CONFIG_FILE
          echo "keyAlias=${{ secrets.KEY_ALIAS }}"           >> $CONFIG_FILE
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}"     >> $CONFIG_FILE
          # print information
          echo "keystore file ($KEYSTORE_FILE):"
          sha256sum $KEYSTORE_FILE
          #echo "config file($CONFIG_FILE):"
          #cat $CONFIG_FILE

      - name: Build with Gradle (Assemble CheckoutDebug)
        run: |
          ./gradlew assembleCheckoutDebug --stacktrace --parallel

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: dev
          path: ./app/build/outputs/apk/*/debug/*.apk
          retention-days: 3

