name: preview_release
on:
  push:
    tags:
      - "preview_*"
    paths-ignore:
      - "README.md"
      - "version.json"
      - ".github/workflows/preview_release.yml"
      - ".github/workflows/action_test.yml"
      - ".github/ISSUE_TEMPLATE/**"

jobs:
  build:
    name: build preview
    runs-on: ubuntu-18.04
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v2.2.0

      # - uses: gradle/wrapper-validation-action@v1 # its timeout fails the action

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle


      - name: Build with Gradle
        run: ./gradlew assemblePreviewRelease --parallel --stacktrace

      - name: signing apk
        uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: 30.0.3
        with:
          releaseDirectory: ./app/build/outputs/apk/preview/release
          signingKeyBase64: ${{ secrets.KEY }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: preview_release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          retention-days: 30

      - name: Upload mapping.txt
        uses: actions/upload-artifact@v2
        with:
          name: mapping
          path: "app/build/outputs/mapping/preview/release/mapping.txt"

      - name: Release New Version
        uses: softprops/action-gh-release@v1
        id: release_github

        if: startsWith(github.ref, 'refs/tags/preview_')
        with:
          name: "${{ github.ref_name }}"
          files: |
            ${{steps.sign_app.outputs.signedReleaseFile}}
            ${{ github.workspace }}/app/build/outputs/mapping/preview/release/mapping.txt
          prerelease: true
          draft: false
          tag_name: ${{ github.ref }}
          body: Preview Release - ${{ github.ref }}
          body_path: ${{ github.workspace }}/ReleaseNote.md
          token: ${{ secrets.TOKEN }}

      - name: Upload to TG
        uses: appleboy/telegram-action@master

        if: startsWith(github.ref, 'refs/tags/preview_')
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            <b>Preview Version: ${{ github.ref_name }}</b>(<pre>${{ github.sha }}</pre>)
            Preview versions might have potential bugs.
            <b>Preview版本更新!</b> 注意可能存在潜在问题!
            <a href="https://github.com/chr56/Phonograph_Plus/releases/tag/${{ github.ref_name }}"> GitHub Link </a>
          format: html
          document: ${{ github.workspace }}/${{steps.sign_app.outputs.signedReleaseFile}}
          disable_notification: true
          disable_web_page_preview: true
