name: preview_release
on:
  push:
    tags:
      - "preview_*"
    paths-ignore:
      - 'README.md'
      - 'ReleaseNote.md'
      - 'GitHubReleaseNote.md'
      - 'version.json'
      - '.github/**'
      - 'crowdin.yml'
      - 'fastlane/metadata/android/**'

jobs:
  build:
    name: Build&Release Preview
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle (Assemble PreviewRelease)
        run: ./gradlew assemblePreviewRelease --parallel --stacktrace

      - name: signing apk
        uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: 33.0.0
        with:
          releaseDirectory: ./app/build/outputs/apk/preview/release
          signingKeyBase64: ${{ secrets.KEY }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: preview_release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          retention-days: 30

      - name: Upload mapping.txt
        uses: actions/upload-artifact@v3
        with:
          name: mapping
          path: ./app/build/outputs/mapping/previewRelease/mapping.txt

      - name: Release New Version
        uses: softprops/action-gh-release@v1
        id: release_github
        if: startsWith(github.ref, 'refs/tags/preview_')
        with:
          name: "${{ github.ref_name }}"
          files: |
            ${{steps.sign_app.outputs.signedReleaseFile}}
            ${{ github.workspace }}/app/build/outputs/mapping/previewRelease/mapping.txt
          prerelease: true
          draft: false
          tag_name: ${{ github.ref }}
          body: Preview Release - ${{ github.ref }}
          body_path: ${{ github.workspace }}/GitHubReleaseNote.md
          token: ${{ secrets.TOKEN }}

      - name: Upload to Channel
        if: startsWith(github.ref, 'refs/tags/preview_')
        run: |
          curl -v -X POST -H "Content-Type:multipart/form-data"  -F 'document=@${{ github.workspace }}/${{steps.sign_app.outputs.signedReleaseFile}}'  "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.TG_CHAT_ID }}&disable_notification=true&disable_web_page_preview=true&parse_mode=HTML&caption=New%20Preview%20Version!%20%3Cb%3E${{ github.ref_name }}%3C%2Fb%3E(%3Cpre%3E${{ github.sha }}%3C%2Fpre%3E)%20%0APreview%20versions%20might%20have%20potential%20bugs.%0A%3Cb%3EPreview%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0!%3C%2Fb%3E%20%E6%B3%A8%E6%84%8F%E5%8F%AF%E8%83%BD%E5%AD%98%E5%9C%A8%E6%BD%9C%E5%9C%A8%E9%97%AE%E9%A2%98!%0A%3Ca%20href%3D%22https%3A%2F%2Fgithub.com%2Fchr56%2FPhonograph_Plus%2Freleases%2Ftag%2F${{ github.ref_name }}%22%3E%20GitHub%20Link%20%3C%2Fa%3E"
          ./gradlew encodeReleaseNoteToUrl
          RELEASE_NOTE=$(cat ${{ github.workspace }}/GithubReleaseNote.url.txt)
          curl -v "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TG_CHAT_ID }}&disable_notification=true&disable_web_page_preview=true&parse_mode=Markdown&text=$RELEASE_NOTE"