name: preview_release
on:
  push:
    tags:
      - "preview_*"
    paths-ignore:
      - "README.md"
      - "version.json"
      - '.github/workflows/preview_release.yml'
      - '.github/workflows/action_test.yml'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build:
    name: build preview
    runs-on: ubuntu-18.04
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v2.2.0

      # - uses: gradle/wrapper-validation-action@v1 # its timeout fails the action

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle

#      # now we are use Android Gradle Plugin 7.0.*
#
#      - name: Create DX links for BuildTools
#        run: ln -s $ANDROID_HOME/build-tools/31.0.0/d8 $ANDROID_HOME/build-tools/31.0.0/dx && ln -s $ANDROID_HOME/build-tools/31.0.0/lib/d8.jar $ANDROID_HOME/build-tools/31.0.0/lib/dx.jar
#        # we are using Android Gradle Plugin 4.x.x, which can not find 'dx' in SDK31
#

      - name: Build with Gradle
        run: ./gradlew assemblePreview --stacktrace

      - name: signing apk
        uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: 30.0.3
        with:
          releaseDirectory: ./app/build/outputs/apk/preview
          signingKeyBase64: ${{ secrets.KEY }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: preview_release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          retention-days: 30


      - name: Upload mapping.txt
        uses: actions/upload-artifact@v2
        with:
          name: mapping
          path: "app/build/outputs/mapping/preview/mapping.txt"

      - name: Release New Version
        uses: softprops/action-gh-release@v1
        id: release_github

        if: startsWith(github.ref, 'refs/tags/preview_')
        with:
          name: "[Preview] ${{ github.ref_name }}"
          files: |
            ${{steps.sign_app.outputs.signedReleaseFile}}
            ${{ github.workspace }}/app/build/outputs/mapping/preview/mapping.txt
          prerelease: true
          draft: false
          tag_name: ${{ github.ref }}
          body: Preview Release - ${{ github.ref }}
          body_path: ${{ github.workspace }}/ReleaseNote.md
          token: ${{ secrets.TOKEN }}

      - name: Upload to TG
        uses: appleboy/telegram-action@master

        if: startsWith(github.ref, 'refs/tags/preview_')
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            <b>New Preview Version!</b>
            <b>${{ github.ref_name }}</b> (<pre>${{ github.sha }}</pre>)
            <b>Preview版本更新!</b>

            <a href="https://github.com/chr56/Phonograph_Plus/releases/tag/${{ github.ref_name }}"> GitHub Link </a>
            <pre>${{ github.action_path }}</pre>
          format: html
          document: ${{ github.workspace }}/${{steps.sign_app.outputs.signedReleaseFile}}
          disable_notification: true
          disable_web_page_preview: true
